### ISSUE TITLE
Error installing on py27

### ISSUE THREAD

**Issue by tlansec** [censys/censys-command-line#1]
Installing on Py2.7 yields the following error:
```
λ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    with open(path.join(current_dir, 'README.md'), encoding='utf-8') as f:
TypeError: 'encoding' is an invalid keyword argument for this function
```

Using the io module to open the file will fix this:

https://stackoverflow.com/questions/25049962/is-encoding-is-an-invalid-keyword-error-inevitable-in-python-2-x

**Comment by artsturdevant** [comment]
Most recent commit should resolve this issue.
