### ISSUE TITLE
Many IPv4 Addresses Do Not Return Data

### ISSUE THREAD

**Issue by ag100** [censys/censys-command-line#4]
When querying IPv4 addresses, many IPs do not return data, even when there's valid data shown in the raw data on the web page.   Example:

https://censys.io/ipv4/74.121.34.41/raw - Shows:

{
  "ip": "74.121.34.41", 
  "autonomous_system": {
    "description": "PSD-ROCKET-AS - PSD Professional Systems/Designs, Ltd, CA", 
    "routed_prefix": "74.121.32.0/22", 
    "country_code": "CA", 
    "organization": "PSD Professional Systems/Designs, Ltd, CA", 
    "asn": 26968, 
    "name": "PSD-ROCKET-AS"
  }, 
  "location": [
    {
      "city": "North Vancouver", 
      "subdivision_2_code": "", 
      "country": "Canada", 
      "subdivision_1": "British Columbia", 
      "time_zone": "America/Vancouver", 
      "longitude": -123.1149, 
      "continent": "North America", 
      "locale_code": "en", 
      "subdivision_1_code": "BC", 
      "postal_code": "V7P", 
      "continent_code": "NA", 
      "country_code": "CA", 
      "subdivision_2": "", 
      "latitude": 49.322, 
      "metro_code": "", 
      "is_anonymous_proxy": false, 
      "is_satellite_provider": false
    }
  ]
}

Querying via the command line below does not return results (and seems to work fine with other IPs).  

/usr/local/bin/censys_command_line.py ip:74.121.34.41 --query_type ipv4 --fields autonomous_system

/usr/local/bin/censys_command_line.py ip:74.121.34.41 --query_type ipv4 --fields location

I'll dig into this a bit in the next few days to see if I can figure it out, but wanted to open an issue in case there's a (non-end user) bug.  Thanks.

**Comment by artsturdevant** [comment]
Hi, 

Thanks for the ticket. It looks like this isn't a bug with this project. The Censys service isn't returning any data since it only has data from whois. I'll open a bug internally. I agree it's confusing to show it differently depending on how you view the host webUI vs API.

Thanks!
