### ISSUE TITLE
Error: dict contains fields not in fieldnames: [...]

### ISSUE THREAD

**Issue by OSINT-d** [censys/censys-command-line#8]
Hi everyone,
I find troubles using the following censys query:

**censys "PARAMETER" --query_type=ipv4 --fields ip --censys_api_id *** --censys_api_secret *** --max_pages 10 --output csv**

The terminal shows me this error:

**error writing log file. Error: dict contains fields not in fieldnames: '23.telnet.banner.banner', '23.telnet.banner.support'**

What does it means? There is a way to bypass it?

Thank you!

**Comment by thehappydinoa** [comment]
Hi, this issue has been fixed in [censys/censys-python  >= 1.0.0](https://github.com/censys/censys-python). Please let me know if you have more questions.
